### ISSUE TITLE
Content not displayed

### ISSUE THREAD

**Issue by pyladune** [fewlinesco/bamboo_smtp#1]
Is there a trick (or a bug ?) in the fact that content of HTML emails are just not displayable in emails clients except gmail ?

**Comment by tgautier** [comment]
No there's no trick on our side, and if there's a bug, we haven't found it (yet).

Could you please give us more information regarding the bug and the context/use case?

**Comment by pyladune** [comment]
We are able to use bambo with local adapter without issue,
When using the SMTP adapter, emails are sent but the content is not readable except in gmail.
In case reading the gmail account from thunderbird or as well has sending to hotmail adress, the HTML content can not be displayed (if a full text content is available then it is displayed instead).
We tried with 2 different SMTP servers.
[no content displayed message.txt](https://github.com/fewlinesco/bamboo_smtp/files/289747/no.content.displayed.message.txt)

**Comment by hubertlepicki** [comment]
I have tracked down the issue @pyladune the pull request is here:

https://github.com/fewlinesco/bamboo_smtp/pull/2
