### ISSUE TITLE
Direct call to Bamboo.Mailer.deliver_now returns (UndefinedFunctionError) function nil.send_blocking/2 is undefined or private

### ISSUE THREAD

**Issue by buob** [fewlinesco/bamboo_smtp#106]
Hi guys!  Thanks for the lib!  It looks like there's a config that is being expected, `transport`, on which there isn't any documentation.  It also looks like the default should be coming through there but maybe it isn't?

I'm calling `Bamboo.Mailer.deliver_now` directly, so that might have something to do with it?

```
(UndefinedFunctionError) function nil.send_blocking/2 is undefined or private
```

**Comment by kdisneur** [comment]
Hi!

Yes the config is not documented as it's not intended to be publicly used. it's just a convenient way to mock `:gen_smtp_client` behaviour in the tests.

In the code, I can read:

```elixir
# lib/bamboo/adapters/smtp_adapter.ex:243
Map.put_new(config, key, default_value)
```

It means if the value has been set to `nil` somehow, we will not override the value with `:gen_smtp_client`. I imagine you don't set the key to `nil` in your `config.exs` file?

Do you have a bit more context about how you use / configure the library?

**Comment by tgautier** [comment]
Closing stale issue.

**Comment by alex88** [comment]
@buob did you find any workaround on this? I'm calling deliver_now directly too because I read the config dynamically and it's not static (we have our customers save the smtp config) and I'm having the same issue
