### ISSUE TITLE
Implement DSN

### ISSUE THREAD

**Issue by blacksph3re** [fewlinesco/bamboo_smtp#108]
As described in [rcf3461](https://tools.ietf.org/html/rfc3461) smtp supports delivery status notifications. It would be nice to have a way to check on DSNs for an email to see if it failed to deliver

**Comment by kdisneur** [comment]
That's a good idea but I don't know if it's possible to implement.

We rely on [gen_smtp](https://github.com/Vagabond/gen_smtp) to send the emails and I don't see any keywords coming from the DSN spec anywhere (RET, NOTIFY,...) in the repository.

I would suggest to contact the gen_smtp maintainer. I can see [an open issue](https://github.com/Vagabond/gen_smtp/issues/161) there but no replies.

**Comment by tgautier** [comment]
Closed as there is still no sign from 
https://github.com/Vagabond/gen_smtp/issues/161 on the support of DSN.

Feel free to reopen this issue if support is coming.

**Comment by mworrell** [comment]
Passing by, as this is referring to an issue in gen_smtp.

What features are you looking for?  An option to specify DSN when sending emails?
