### ISSUE TITLE
Amazon SES - Emails with only bcc recipients not working. 

### ISSUE THREAD

**Issue by Ivor** [fewlinesco/bamboo_smtp#110]
Hi. 

I have an email that is sent to a user defined list of recipients, and it bcc'ed to a app-level list of recipients. If the user leaves the `to` recipients empty, I want the email to still go out to the `bcc` recipients. 

I am using Amazon SES. 

Is there a problem sending emails without any recipients in the `to` header, if there are recipients in the `bcc` header? 

The error I am getting is: 

```
** (Bamboo.SMTPAdapter.SMTPError) There was a problem sending the email through SMTP.

The error is :no_more_hosts

More detail below:

{:permanent_failure, 'email-smtp.us-west-2.amazonaws.com', "554 Transaction failed: Empty required header 'To'.\r\n"}
```

For clarity, the emails send fine if there is one or more email addresses defined by the user.

**Comment by kdisneur** [comment]
Hi,

BambooSMTP doesn't have any validation about number of recipients.

The error (`554 Transaction failed`) is an error coming from the SMTP Server. The error description `Empty required header 'To'` suggests Amazon SES doesn't allow to send emails containing only BCCs recipients.:confused:

To confirm the problem comes from Amazon SES, I tried to send an email using only BCCs to a GMail SMTP server and it works fine.

**Comment by tgautier** [comment]
I'm closing this issue as it seems to be a configuration problem.

Feel free to reopen the issue if it's not the case.

**Comment by speeddragon** [comment]
I'm trying to send an email to a list of emails without a `to`, but this is happening:

```
[error] Task #PID<0.948.0> started from #PID<0.941.0> terminating
** (stop) {:nocatch, {:permanent_failure, "501 Invalid RCPT TO address provided\r\n"}}
    (gen_smtp) /project/deps/gen_smtp/src/gen_smtp_client.erl:309: :gen_smtp_client.try_RCPT_TO/4
    (gen_smtp) /project/deps/gen_smtp/src/gen_smtp_client.erl:268: :gen_smtp_client.try_sending_it/4
    (gen_smtp) /project/deps/gen_smtp/src/gen_smtp_client.erl:193: :gen_smtp_client.send_it/2
    (bamboo_smtp) lib/bamboo/adapters/smtp_adapter.ex:77: Bamboo.SMTPAdapter.deliver/2
    (elixir) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Function: #Function<0.51449392/0 in Bamboo.TaskSupervisorStrategy.deliver_later/3>
    Args: []
```

Via cURL I can send the email to a list of email addresses as BCC.

```
curl -v --mail-from 'support@verifieddomain.com' --mail-rcpt 'success@simulator.amazonses.com' --user 'user:pass' --ssl-reqd 'smtp://email-smtp.eu-west-1.amazonaws.com:587' -T ./message.txt
```

```
message.txt

From: <support@verifieddomain.com>
Bcc: <email@example.com>, <email2@example.com>
Subject: Curl Test Bcc
```

It looks like it wasn't implemented yet in `gen_smtp`, https://github.com/gen-smtp/gen_smtp/issues/11
