### ISSUE TITLE
Deprecation warnings

### ISSUE THREAD

**Issue by fireproofsocks** [fewlinesco/bamboo_smtp#111]
The following warnings are observed on 
Elixir 1.8.1 (compiled with Erlang/OTP 21)

```
src/smtp_util.erl:71: Warning: crypto:rand_uniform/2 is deprecated and will be removed in a future release; use rand:uniform/1
src/smtp_util.erl:71: Warning: crypto:rand_uniform/2 is deprecated and will be removed in a future release; use rand:uniform/1
src/socket.erl:124: Warning: ssl:ssl_accept/1: deprecated; use ssl:handshake/1 instead
src/socket.erl:233: Warning: ssl:ssl_accept/3: deprecated; use ssl:handshake/3 instead
```

**Comment by kdisneur** [comment]
Yes it's coming from [`gen_smtp`](https://github.com/Vagabond/gen_smtp).

[A pull-request has been opened some months ago](https://github.com/Vagabond/gen_smtp/pull/156) but can't be merged as it is, because the suggested functions (i.e.`ssl:handshake`) did not exist in previous OTP versions.
