### ISSUE TITLE
Only Base64-encode headers when necessary

### ISSUE THREAD

**Issue by blacksph3re** [fewlinesco/bamboo_smtp#112]
Spam filters dislike base64-encoded email headers, as it was used to circumvent earlier spam filters.  [click](https://wiki.apache.org/spamassassin/Rules/FROM_EXCESS_BASE64)  However, the adapter always base64-encodes, regardless of whether it is actually necessary.
Can we extend the `rfc822_encode` method to check before base64 encoding if there are actually any non-ascii-127 characters in the data?

I would be willing to help with a PR...

**Comment by tgautier** [comment]
Hey,

We would gladly accept a PR for this issue.

I am wondering if we also need to do this for other parts of the emails that may contain non us-ascii characters such as the body (we specify `utf-8` for the content) or the sender/recipients (that we also `rfc822_encode`)?

**Comment by arnaudmorisset** [comment]
Hello @blacksph3re 👋 

This feature is available in our latest release: https://github.com/fewlinesco/bamboo_smtp/releases/tag/v3.1.0

I hope it will be useful. 🙂
