### ISSUE TITLE
update gen_smtp to 0.14.0

### ISSUE THREAD

**Issue by ckruse** [fewlinesco/bamboo_smtp#114]
The release of Erlang/OTP 22 brought a new `:socket` API, creating a name conflict between gen_smtp and OTP (see http://blog.erlang.org/OTP-22-Highlights/). gen_smtp released a new version to address this issue. Can you please update dependencies?

**Comment by ckruse** [comment]
Ping? :-) Don't want to nag you, but is there a chance of an update?

**Comment by tgautier** [comment]
Thanks for the ping!

You should see a new release before the end of the week.

**Comment by julien-leclercq** [comment]
@ckruse the dependencies updates you requested have been published in the `1.7.0` version.

**Comment by ckruse** [comment]
Thanks a lot!
