### ISSUE TITLE
DKIM support?

### ISSUE THREAD

**Issue by ghost** [fewlinesco/bamboo_smtp#120]
👋

First of all, thank you for the package!

Second of all ... Is there a way to use `:gen_smtp`'s [ability](https://github.com/Vagabond/gen_smtp#dkim-signing-of-outgoing-emails) to DKIM sign the messages?

I think it would need to be introduced into the [`body/1`](https://github.com/fewlinesco/bamboo_smtp/blob/add8abec0fd0f116b25cca1122312c36acceee19/lib/bamboo/adapters/smtp_adapter.ex#L271) function (somewhere at the end), and the DKIM options can be put into `Bamboo.Email`'s [`:private`](https://github.com/thoughtbot/bamboo/blob/9a33d92c5955d9ca3713d8d5060978896aa6d394/lib/bamboo/email.ex#L86) field?

**Comment by kdisneur** [comment]
Hi 👋

Thanks for the issue. Yes DKIM would be a nice feature to support.

> I think it would need to be introduced into the body/1 function (somewhere at the end)

👍

> and the DKIM options can be put into Bamboo.Email's `:private` field 

We currently store all the configuration in `config.exs` (server, username, password, ..), shouldn't we keep the path to the private key in the configuration file to be consistent?

**Comment by ghost** [comment]
> We currently store all the configuration in `config.exs` (server, username, password, ..), shouldn't we keep the path to the private key in the configuration file to be consistent?

Sure, didn't think of that. I'll try to make a PR over the next few days.

**Comment by ghost** [comment]
@kdisneur I've achieved a somewhat working version with forking both `gen_smtp` and `bamboo_smtp`. In the former I [made](https://github.com/gen-smtp/gen_smtp/compare/master...syfgkjasdkn:make-dkim-public) the `dkim_sign_email/3` function public, and in the latter I had to [drop](https://github.com/syfgkjasdkn/bamboo_smtp/commit/a8c76aa4df2e36b684324b0b8180515af158c8db) a lot of extra stuff to make the output be equal to that of `gen_smtp`. Unfortunately, it proved to be a bit more complicated than I expected, and I think I'll have to postpone any further work on it until I actually need anything other than singing text messages (which the two forks above already work with, but in its current form it's not ready for a proper PR) ...
