### ISSUE TITLE
Getting TLS error when sending email

### ISSUE THREAD

**Issue by egeersoz** [fewlinesco/bamboo_smtp#138]
I am getting this error when trying to send an email:

```
{:network_failure, 'smtp.office365.com', {:error, {:tls_alert, 'bad record mac'}}}

        (bamboo_smtp) lib/bamboo/adapters/smtp_adapter.ex:96: Bamboo.SMTPAdapter.handle_response/1
        (bamboo) lib/bamboo/mailer.ex:145: Bamboo.Mailer.deliver_now/4
```

```
server: "smtp.office365.com",
username: "someone@mydomain.com",
password: "somepass",
port: 587,
ssl: true,
tls: :always,
allowed_tls_versions: [:"tlsv1.2"],
auth: :always,
retries: 1
```

There are several other applications on my computer (Microsoft Outlook, as well as another .NET application) that can send emails via this SMTP server without issues. However, my Phoenix application fails with the above error.

edit: I should mention that I'm on Windows 10. I just tried on another Windows 10 machine and got the same error.

**Comment by egeersoz** [comment]
It seems to work when I set `ssl` to false. I don't understand why, though. Shouldn't the `tls` setting take precedence?

**Comment by kdisneur** [comment]
Hi. 

I'm not an expert about SSL and TLS to be honest. We just added all the options available in `gen_smtp` to make sure anyone can configure Bamboo the way they need. 

I don't know how it's implemented, sorry. You might get more help on https://github.com/gen-smtp/gen_smtp.

I will close it as it looks like you resolved it by setting the options in "the correct order". Don't hesitate to reopen if we can be of any help.
