### ISSUE TITLE
Connect per IPv6

### ISSUE THREAD

**Issue by genofire** [fewlinesco/bamboo_smtp#143]
Hello,
i try to connect to a smtp server per ipv6 - which was not possible, even with:
```elixir
family: :inet6
```
as parameter (and hacky by change it in code here):
https://github.com/fewlinesco/bamboo_smtp/blob/afb298e13ff2f5453ffc4a8f6971ed6a44e35680/lib/bamboo/adapters/smtp_adapter.ex#L43

I always got: 
```elixir
{:network_failure, 'mx01.example.org', {:error, :enetunreach}}
```

**Comment by MatheusBueno782** [comment]
Hello @genofire and sorry for taking too long to answer.

 Do you still have the issue? if yes, could you give us more information about it? I little bit more of code and context will help me to give you a more precise answer.

thanks!

**Comment by Fnux** [comment]
That issue happens when you try to connect to a SMTP when in an IPv6-only environment. Erlang makes a difference between the `:inet` and `:inet6` families, which usually needs to be specified by hand.

I just hit this - my production environment is IPv6-only - and will patch it.

**Comment by Fnux** [comment]
https://github.com/fewlinesco/bamboo_smtp/blob/develop/lib/bamboo/adapters/smtp_adapter.ex#L524 <- the `:family` option is not handled in `to_gen_smtp_server_config`.

**Comment by Fnux** [comment]
Ah, it's not the gen_smtp server but client config, my bad. We need to specify the sockopts option of gen_smtp_client.

**Comment by Fnux** [comment]
Erk. `sockopts` is not simply passed to `gen_tcp` but processed by `smtp_socket` (https://github.com/gen-smtp/gen_smtp/blob/master/src/smtp_socket.erl). The later doesn't seem to care much about IPv6...

**Comment by Fnux** [comment]
After some erlang-reading: `inet6` is indeed passed to `gen_tcp`, but along side the default `{:ip, {0,0,0,0}}` which should be `{:ip, {0,0,0,0,0,0,0,0}}`.

**Comment by MatheusBueno782** [comment]
Hey @Fnux. 

Thanks a lot for your contribution! We already merged your patch and it is available in our latest release. I'm closing this issue since it's now solved.
