### ISSUE TITLE
{:nocatch, {:permanent_failure, "501 Invalid command or cannot parse to address\r\n"}}

### ISSUE THREAD

**Issue by pacoguzman** [fewlinesco/bamboo_smtp#148]
Hi there,

We're seeing the following entries in the log of one of our service that make use of bamboo_smtp. Would be possible to catch those throws from the gen_smtp_client library and re-raise `SMTPError` so we can debug what is missing. Or if there is other way to debug this?

I would say reading the `bamboo` code that a validation and normalization of addresses happens before delivering the email so shouldn't that catch this issues?

Thanks in advance

**Comment by MatheusBueno782** [comment]
Hi @pacoguzman ,

Sorry for taking so long to answer. We just solved the issue, for now on you shouldn't only receive errors in `SMTPError` format. 

Thank you very much and If you have any further questions i will be glad to answer.
