### ISSUE TITLE
SendGrid will soon stop supporting auth with username and password

### ISSUE THREAD

**Issue by riverKanies** [fewlinesco/bamboo_smtp#164]
I need to update my sendgrid integration to authenticate with an API key but it seems this lib does not support that...?

**Comment by riverKanies** [comment]
actually I can just use the new SendGridAdapter, but seems like it would be a good thing to add anyway

**Comment by arnaudmorisset** [comment]
Hello! :wave:

Thanks for the suggestion but it might be out of scope for this library.

From a theoretical point of view, BambooSMTP should be used as an adapter for "raw" SMTP usage. It's targeting folks who want to use their self-hosted SMTP or a managed one like Amazon SES. If you plan to use a full-featured email delivery service (SendGrid, MailChimp, MailJet, ...), creating/using a dedicated adapter will be a better fit.

From a more technical point of view, BambooSMTP is just a layer of abstraction above GenSMTP_Client, an Erlang library that follows SMTP RFC(s). That means that they don't support API Key based authentication, only basic auth with username and password. Adding third party custom authentication layer above GenSMTP is then out of scope for this library.

Thanks again for reaching us, and I hope the SendGrid adapter will be a good fit for your project. :slightly_smiling_face:
