### ISSUE TITLE
Content Display Problem in Apple Mail

### ISSUE THREAD

**Issue by bigcurl** [fewlinesco/bamboo_smtp#17]
The following mail does not display content in Apple Mail. The content is displayed on Googles Gmail Web site though.

```
new_email(
to: "test@gmail.com",
from: "test@example.com",
subject: "Testing Bamboo",
html_body: "<h1>Hey</h1><p>Check out this email or else.</p>",
text_body: "# Hey\n\nCheck out this email or else."
```

You'll find a small project here [bamboo_gmail_test](https://github.com/bigcurl/bamboo_gmail_test) that I used to send the mail. Files of interest are

`config/config.exs` where `Bamboo.SMTPAdapter` is defined.
`lib/send_gmail.ex` where the mail creation code is defined.
Mail is send by running `iex` and `SendGmail.Email.welcome_email |> SendGmail.Mailer.deliver_later`

I opened a ticket with Bamboo first but they refered me here: [bamboo/issues/193](https://github.com/thoughtbot/bamboo/issues/193)

**Comment by tgautier** [comment]
Thanks for letting us know.

We're going to have a look.

**Comment by kdisneur** [comment]
Hey @bigcurl, we are really sorry to not have spent time on this issue before.

Today I cloned your repository and manage to reproduce your error on Apple Mail. I don't know what was broken **BUT**, after I updated your `mix.exs` on the latest versions of Bamboo & BambooSMTP, it's working.

So, I would just suggest to upgrade your versions. Sorry again for the late reply.

![](http://take.ms/ebnYJ)
