### ISSUE TITLE
Cannot install dependency on phoenix 1.5.7

### ISSUE THREAD

**Issue by LatitudeAdjustment** [fewlinesco/bamboo_smtp#172]
- Cannot install dependency on phoenix 1.5.7

- Relates to issue https://github.com/fewlinesco/bamboo_smtp/issues/167

- Relates to pull request https://github.com/fewlinesco/bamboo_smtp/pull/171

- Core dependency gen_smtp was recently upgraded to 1.1.0 for Ranch >= 1.7.0.

- gen_smtp was recently updated to 1.1.0 in Swoosh v1.3.2

https://github.com/swoosh/swoosh/pull/571

**Comment by babariviere** [comment]
This issue can now be closed as #171 is merged
