### ISSUE TITLE
Support for Bamboo 2.2

### ISSUE THREAD

**Issue by LeandroLM** [fewlinesco/bamboo_smtp#197]
I've tried to update Bamboo in my app to version `2.2` and BambooSMTP to `4.0` but I couldn't because BambooSMTP `4.0.1` specifies Bamboo `~> 2.1.0`. How can I solve this? Can I open an PR to change bamboo dep to `~> 2.2` or `>= 2.1.0`?

**Comment by babariviere** [comment]
Hi @LeandroLM, I will try to update Bamboo version to `2.2`

**Comment by babariviere** [comment]
Hi @LeandroLM, looks like we are already using version `2.2`, so I will close this issue
