### ISSUE TITLE
Upgrading to Heroku-20 stack (Ubuntu 20.04) seems to cause emails to not be sent

### ISSUE THREAD

**Issue by jay-meister** [fewlinesco/bamboo_smtp#202]
After upgrading to heroku 20 stack, emails are no longer being sent from production.

There is some TLS information given here in the upgrade notes:
https://devcenter.heroku.com/articles/heroku-20-stack#upgrading-to-heroku-20

I have set the following config to no avail:

```
config :ev2, Ev2.Mailer,
  adapter: Bamboo.SMTPAdapter,
  server: System.get_env("SES_SERVER"),
  port: System.get_env("SES_PORT"),
  username: {:system, "SES_SMTP_USERNAME"},
  password: {:system, "SES_SMTP_PASSWORD"},
  # tls version 1.2 is required for later versions of ubuntu (20.04)
  # and thus is required for use with the heroku-20 stack
  allowed_tls_versions: [:"tlsv1.2"],
  tls: :always,
  retries: 5
```

Locally everything works fine.

Could anyone assist with which other configuration steps I might need?

**Comment by jay-meister** [comment]
Closing as this wasn't the cause.

Heroku / SES seemed to suddenly timeout on all requests on PORT 25. Changing to SES port 587 did the trick.

**Comment by kdisneur** [comment]
> Closing as this wasn't the cause.
> 
> Heroku / SES seemed to suddenly timeout on all requests on PORT 25. Changing to SES port 587 did the trick.

Heroku is running on AWS (as fars as I know) and AWS used to throttle outbound connections on port 25 on EC2. Maybe it could explain... Although I just found out they now entirely block it https://aws.amazon.com/premiumsupport/knowledge-center/ec2-port-25-throttle/ 🤔 

Anyway if possible, it always preferable to use 587 over 25.

EDIT: Heroku also seems to document this intermittent timeout in their documentation https://help.heroku.com/IR3S6I5X/problem-in-sending-e-mails-through-smtp
