### ISSUE TITLE
bamboo_smtp dependencies warning (hut)

### ISSUE THREAD

**Issue by masoudgs** [fewlinesco/bamboo_smtp#206]
Hi Bamboo SMTP, Recently i'm getting warnings from `hut` dependency. It looks some rebar modifications need for hut.

https://github.com/tolbrino/hut/issues/18

**Comment by alappe** [comment]
From what I read it's fixed in `gen_smtp v1.2`: https://github.com/gen-smtp/gen_smtp/issues/312

**Comment by kyleboe** [comment]
I opened [this PR](https://github.com/fewlinesco/bamboo_smtp/pull/205). Just need to adjust deps to get CI passing.

**Comment by tgautier** [comment]
Fixed by #205
