### ISSUE TITLE
Switch over to :gen_smtp or other battle proven solution from string concatenation

### ISSUE THREAD

**Issue by hubertlepicki** [fewlinesco/bamboo_smtp#3]
So I was just wondering why do you guys create the email content from scratch? Why not use something like https://github.com/Vagabond/gen_smtp ?

The thing is, it'll get quite complicated to assemble more advanced emails with attachments, multipart etc.

We need that at, and at some point it will be an issue to us. Can I do some work to port code from, say https://github.com/swoosh/swoosh/blob/master/lib/swoosh/adapters/smtp.ex to your project?

Otherwise I'll have to set up `bamboo_smtp_2` project and I would hate maintaining it :P

**Comment by kdisneur** [comment]
Excellent question. I guess the best answer is: "I'm not really confident with Erlang, and I didn't understood we could build an email using the lib. I just used it to send the email."

Of course, we would be really happy to merge a better implementation! :)
