### ISSUE TITLE
Amazon SES - 553 invalid email address

### ISSUE THREAD

**Issue by syamilmj** [fewlinesco/bamboo_smtp#30]
Trying to set the sender's name with this bit of code:

```
|> from({"John Doe", "johndoe@example.com"})
```

and that gives me an error:

```
553 <John Doe<johndoe@example.com> invalid email address
```

Apparently in `gen_smtp`, we have this line that wraps the email field as such:

```
try_MAIL_FROM(From, Socket, Extensions) ->
    % someone was bad and didn't put in the angle brackets
    try_MAIL_FROM("<"++From++">", Socket, Extensions).
```

Locally, via `mailcatcher` ruby gem I can see that the request went through just fine, but the From field is set to `<John Doe<johndoe@example.com>>`. I'm not sure if this is the correct format but maybe that's where the issue is, or maybe the bamboo_smtp is sending the wrong format?

Thanks!

**Comment by tgautier** [comment]
We have reproduced the error, we're looking at a fix.

**Comment by syamilmj** [comment]
Thanks, will be sending PR if that's any help.

**Comment by tgautier** [comment]
Thanks a lot for your detailed bug report, the culprit was indeed the formating of from/to by gen_smtp.

We'll release a new version very soon.

**Comment by tgautier** [comment]
We just released `v1.2.1` https://hex.pm/packages/bamboo_smtp/1.2.1

**Comment by syamilmj** [comment]
That was quick! Thanks @tgautier

**Comment by tgautier** [comment]
We actually had the problem too, hence the speed 😉 

Cheers!
