### ISSUE TITLE
Bamboo.SMTPAdapter.SMTPError network_failure

### ISSUE THREAD

**Issue by erincat** [fewlinesco/bamboo_smtp#36]
Tried to send an email with our own smtp server but I always get this error

** (Bamboo.SMTPAdapter.SMTPError) There was a problem sending the email through SMTP.
The error is :retries_exceeded
More detail below:
{:network_failure, "xxx.domain.com", {:error, :timeout}}

But I am connected to the server.

**Comment by tgautier** [comment]
I think you may have a real connectivity issue.

The error you're getting doesn't come from BambooSMTP but from the underlying `gen_smtp` library, we're just passing it through.

**Comment by fteem** [comment]
@erincat did you solve this problem? I think that I am experiencing the same issue with Amazon SES.

**Comment by Rodeoclash** [comment]
I'm getting this as well with Amazon SES. Can connect correctly using Telnet + port. Odd.

**Comment by fteem** [comment]
@Rodeoclash see [this](https://github.com/hexpm/hex_web/pull/418#issuecomment-269561943), it might help you.

**Comment by Rodeoclash** [comment]
@fteem Great find, thanks!

EDIT: Just removed the `ssl: true` line from the config and emails are being sent.
