### ISSUE TITLE
Error when sending email using SMTP Adapter and Amazon SES

### ISSUE THREAD

**Issue by lmatayoshi** [fewlinesco/bamboo_smtp#40]
This is my configuration of the Mailer:

```
config :app, App.Mailer,   
   adapter: Bamboo.SMTPAdapter,
   server: "email-smtp.us-east-1.amazonaws.com",
   port: x, # x in [25, 465, 587]
   username: "user",
   password: "password",
   tls: :always, # can be `:always` or `:never`
   retries: 1
```

No matter what port I use, I get an error when trying to send an email. These are the errors for each
port:

```
25 -> {:permanent_failure, "email-smtp.us-east-1.amazonaws.com", "530 Authentication required\r\n"}
```

```
465 -> {:network_failure, "email-smtp.us-east-1.amazonaws.com", {:error, :closed}}
```

```
587 -> {:permanent_failure, "email-smtp.us-east-1.amazonaws.com", "530 Authentication required\r\n"} 
```

I've already tried removing `ssl: true`, as suggested in https://github.com/fewlinesco/bamboo_smtp/issues/36

**Comment by kdisneur** [comment]
Hello, 

We also use `AWS SES`, here the configuration we have to send emails:

```elixir
config :app_name, AppName.Mailer,
  adapter: Bamboo.SMTPAdapter,
  server: "email-smtp.eu-west-1.amazonaws.com",
  port: 587,
  username: {:system, "AWS_ACCESS_KEY_ID"},
  password: {:system, "AWS_SECRET_ACCESS_KEY"},
  tls: :always,
  ssl: false,
  retries: 1
```

Your error message says "530 Authentication required". Are you sure your credentials are valid?

**Comment by tgautier** [comment]
Moreover, the credentials of the AWS user you're using must have the proper SES policy (rights).

**Comment by kdisneur** [comment]
If you still have problems, feel free to reopen the issue. :)

**Comment by wfgilman** [comment]
@kdisneur I was having the same problem. Of the ports listed by AWS as available, 25, 465 or 587, only 587 works. The rest returns the `:network_failure` error by Bamboo.
