### ISSUE TITLE
Update README and config.exs to reflect recent changes on username and password

### ISSUE THREAD

**Issue by tgautier** [fewlinesco/bamboo_smtp#48]
Changes introduced by #37

**Comment by juhalehtonen** [comment]
Hey. Out of curiosity, what are the "recent changes on username and password" that the title of this issue refers to?

**Comment by tgautier** [comment]
Hey,

You can check all updates in the [CHANGELOG](https://github.com/fewlinesco/bamboo_smtp/blob/develop/CHANGELOG.md).

We were refering to PR #37 

I've updated the description for clarity.

Thanks!
