### ISSUE TITLE
Bump Bamboo version

### ISSUE THREAD

**Issue by Linuus** [fewlinesco/bamboo_smtp#5]
Any reason to just support `bamboo ~> 0.5.0`? 0.6.0 has been released. Is it possible to bump the dependency?

**Comment by tgautier** [comment]
Fixed by #7

**Comment by Linuus** [comment]
That was quick! Thanks!

**Comment by tgautier** [comment]
Thanks for the reporting this 😉

**Comment by tgautier** [comment]
We've just released `1.0.0` with the updated version of bamboo.
