### ISSUE TITLE
catch error

### ISSUE THREAD

**Issue by benjamin79** [fewlinesco/bamboo_smtp#50]
Hi, 

thanks for the adapter.

How can i catch an error? For example if the email is not verified. I´d like to write 

> "554 Message rejected: Email address is not verified. 

into the database.

**Comment by kdisneur** [comment]
Hello @benjamin79, do you think this commit could help you to fix your issue?

Basically you could match some specific errors this way:

```elixir
def send_an_email(email) do
  try do
    MyApp.Mailer.deliver_now(email)
  rescue
    error in Bamboo.SMTPAdapter.SMTPError ->
      case error.raw do
        {:retries_exceeded, _} ->
          IO.inspect("I can do some stuff when this error match")
        _ ->
          IO.inspect "I don't care about these ones"
      end
      # Here, I can re-raise the error
      raise error
  end
end
```

**Comment by benjamin79** [comment]
Thank you, looks good. Will give it a try.

**Comment by kdisneur** [comment]
Cool - Let us now if it works as you expect. If it is, we will release it.

**Comment by benjamin79** [comment]
There is 1 `end` too much. It works - almost. For example if i set the wrong to i get the following in error:

`%Bamboo.SMTPAdapter.SMTPError{message: "There was a problem sending the email through SMTP.\n\nThe error is :no_more_hosts\n\nMore detail below:\n\n{:permanent_failure, \"email-server", \"501 Invalid RCPT TO address provided\\r\\n\"}\n"}`

So no `error.raw`. I´m using aws ses if it is important.

**Comment by kdisneur** [comment]
1. too much `end`: Thanks - I will fix the documentation.
2. Are you sure to use the correct branch (i.e: `feature/#50-catch_error`)? The fix is not yet released, we wanted you to test the branch to be sure it works as you expect before creating a new release.

On the branch `feature/#50-catch_error`, the error should be:

```elixir
%Bamboo.SMTPAdapter.SMTPError{
  raw: {:no_more_hosts, {:permanent_failure, \"email-server", \"501 Invalid RCPT TO address provided\\r\\n\"}},
  message: "There was a problem sending the email through SMTP.\n\nThe error is :no_more_hosts\n\nMore detail below:\n\n{:permanent_failure, \"email-server", \"501 Invalid RCPT TO address provided\\r\\n\"}\n"}
```

To use the branch `feature/#50-catch_error`, you need to update your `mix.exs` file to be:

```elixir
defp deps do
  [ # some deps...
    {:bamboo_smtp, github: "fewlinesco/bamboo_smtp", branch: "feature/#50-catch_error"}
  ]
end
```

**Comment by benjamin79** [comment]
Great, works. Thank you.
