### ISSUE TITLE
:gen_smtp_client to string error

### ISSUE THREAD

**Issue by ryanpager** [fewlinesco/bamboo_smtp#53]
When I try to send a stripped down email:

```elixir
Bamboo.Email.new_email(
      from: {"No Reply", "no-reply@mydomain.com"},
      to: [{"Some Guy", "some.guy@domain.com"}],
      subject: "Winner Winner",
      html_body: "<strong>Bamboo is awesome!</strong>",
      text_body: "*Bamboo is awesome!*",
      headers: %{
        "Reply-To" => "another.guy@domain.com"
      })
    |> Mailer.deliver_now
```

I am getting an odd error, 
```
no function clause matching in :gen_smtp_client.to_string/1
```

Is there some call signature im missing, or am I setting this up wrong? I follow the instructions for set up as closely as I could, and no matter what I do it seems to keep throwing this error.

Any help with this would be fgreat.

**Comment by ryanpager** [comment]
A ha -- it was the username / password combination, I had it as an object based on another persons AWS config. I dont know if it can be exposed better (the error), but it might prevent someone from pulling out their hair.

Sorry about that!

**Comment by kdisneur** [comment]
Hi @ryanpager - thanks for the feedback. I'm not sure to understand this:

>  I had it as an object based on another persons AWS config

Do you have a sample configuration?

Thanks!
