### ISSUE TITLE
Long (more than 1000 characters) html email are truncated

### ISSUE THREAD

**Issue by onioman** [fewlinesco/bamboo_smtp#54]
This is standard limitation according to RFC5322.
The solution is to use Content-Transfer-Encoding: Quoted-printable but Bamboo used together with Phoenix has the following problem:
- Phoenix.View.render_to_string does not encode in quoted-printable.
- bamboo_stmp does not add the "Quoted-printable" header.

**Comment by tgautier** [comment]
Hey, thanks for reporting this issue.

As of now, we're only encoding the subject in `base64` and setting explicitely the `Content-Type` as `UTF-8` since that's the default with Elixir.

We were not aware of `Content-Transfer-Encoding: Quoted-Printable` and the 78 character limit [recommendation](https://www.ietf.org/rfc/rfc5322.txt).

We're going to have a look at this to split the email string 😉

**Comment by shivno** [comment]
quoted-printable exists here https://github.com/DockYard/elixir-mail/blob/master/lib/mail/encoders/quoted_printable.ex

**Comment by shivno** [comment]
to get around much more code i did a quick convert to base64, works at least in thunderbird, would you accept a pr for that?

**Comment by kdisneur** [comment]
Sure, we would be more than happy to test/merge this kind of pull request! 💯

Thanks

**Comment by shivno** [comment]
#80

**Comment by shivno** [comment]
ok to merge?

**Comment by PhilWaldmann** [comment]
This is a major problem, because some mailserver reject emails without a warning!
Are there any plans to solve this issue?

**Comment by kdisneur** [comment]
@PhilWaldmann you're right, thanks for the reminder. 

We've merged the pull-request some months ago but forgot to create the new release as we don't really need this feature in our current usage.

You can use `develop` if you need it right now and we will add a task in our ticket manager to prepare a new release in the coming days.

**Comment by kdisneur** [comment]
We just released the new version of Bamboo. Sorry for the delay:
https://github.com/fewlinesco/bamboo_smtp/blob/develop/CHANGELOG.md#300---2020-09-10
