### ISSUE TITLE
Attachment feature request

### ISSUE THREAD

**Issue by arinrare** [fewlinesco/bamboo_smtp#56]
Are there any plans to support attachments for the Bamboo adapter now that Bamboo has the ability to send them?

**Comment by Ghouli** [comment]
There has been pull request pending on this since september, I've been following updates on Bamboo and updating my fork accordingly.

**Comment by arinrare** [comment]
Awesome Ghouli, thanks :)

**Comment by tgautier** [comment]
Things are moving in #35 

Thanks guys!

**Comment by kdisneur** [comment]
It has been merged today and it's available on Hex: https://hex.pm/packages/bamboo_smtp
