### ISSUE TITLE
Release a version with recent changes ?

### ISSUE THREAD

**Issue by kabturek** [fewlinesco/bamboo_smtp#61]
Hey,
There where some changes in the last 5 months and it would be great to bump the version and publish to hex.

**Comment by kdisneur** [comment]
Hi @kabturek 

You are right, there are some awaiting changes. We postponed the new release because we were waiting for https://github.com/fewlinesco/bamboo_smtp/pull/35 to be merged, but, it looks like it's not going to happen really soon.

We will do a new release in the next few days.

**Comment by kdisneur** [comment]
@kabturek A new version has been released: `v1.4.0`. You can have a look to the [CHANGELOG](https://github.com/fewlinesco/bamboo_smtp/blob/develop/CHANGELOG.md) if interested.

**Comment by kabturek** [comment]
thanks @kdisneur!
