### ISSUE TITLE
Why are there both `tls` and `ssl` config options?

### ISSUE THREAD

**Issue by nathanl** [fewlinesco/bamboo_smtp#70]
I'm looking at the docs, and I see that the configuration includes both `tls` and `ssl` keys. Why is that? Does `ssl: true` mean that it's OK to connect using encryption older than TLS 1.0?

**Comment by tgautier** [comment]
Hi,

Both options are supported by `gen_smtp`, you can find more information about this on their documentation [here](https://github.com/Vagabond/gen_smtp/blob/master/README.markdown#options).

I've also found the [FastMail documentation](https://www.fastmail.com/help/technical/ssltlsstarttls.html) to be of good help to understand how and why both options are often available, with the specific case of SMTP.

Cheers.
