### ISSUE TITLE
getting a 501

### ISSUE THREAD

**Issue by wdiechmann** [fewlinesco/bamboo_smtp#71]
My SMTP server works when I telnet to it - but using my Phoenix app spits this out into the erlang.log.4

```
=CRASH REPORT==== 29-Jul-2017::17:07:15 ===
  crasher:
    initial call: Elixir.Bamboo.TaskSupervisorStrategy:-deliver_later/3-fun-0-/0 
    pid: <0.1563.0>
    registered_name: []
    exception exit: {#{'__exception__' => true,
                       '__struct__' => 'Elixir.Bamboo.SMTPAdapter.SMTPError',
                       message => <<"There was a problem sending the email through SMTP.\n\nThe error is :no_more_hosts\n\nMore detail below:\n\n{:permanent_failure, '10.0.0.141', \"501 Syntax error in parameters or arguments.\\r\\n\"}\n">>,
                       raw => {no_more_hosts,
                           {permanent_failure,"10.0.0.141",
                               <<"501 Syntax error in parameters or arguments.\r\n">>}}},
                     [{'Elixir.Bamboo.SMTPAdapter',handle_response,1,
                          [{file,"lib/bamboo/adapters/smtp_adapter.ex"},
                           {line,80}]},
                      {'Elixir.Task.Supervised',do_apply,2,
                          [{file,"lib/task/supervised.ex"},{line,94}]},
                      {proc_lib,init_p_do_apply,3,
                          [{file,"proc_lib.erl"},{line,247}]}]}
      in function  'Elixir.Task.Supervised':exit/4 (lib/task/supervised.ex, line 125)
    ancestors: ['Elixir.Bamboo.TaskSupervisor','Elixir.Bamboo.Supervisor',
                  <0.1286.0>]
    messages: []
    links: [<0.1289.0>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 2586
    stack_size: 27
    reductions: 4790
  neighbours:
```

If anyone can help me rigth now - it would really be a big favour to 35000 scouts currently camping on a jamboree in Denmark (http://spejderneslejr.dk/en)

**Comment by kdisneur** [comment]
Hi @wdiechmann - sorry for the late reply. I hope your scoots are fine :/

The error is coming from the SMTP server and [this website](http://www.serversmtp.com/en/smtp-error) seems to say it's usually due to an invalid email address.

Are you sure you don't have wrong email addresses?

**Comment by wdiechmann** [comment]
Switched to the SendGrid adapter and all is good:)

Cheers - and thanks for getting back to me!
Walther

**Comment by tgautier** [comment]
Hey @wdiechmann,

Sorry to hear about the problem you had with BambooSMTP and your server.

In order for us to investigate and eventually fix this, could you please give us a little bit more information regarding the SMTP server in question?

Ideally, the name and version of the server and the (obfuscated) configuration you were using with Bamboo SMTP? And any other information that might help us.

Thanks a lot! 😉

**Comment by wdiechmann** [comment]
When I get back to my everyday desk I will share all of that of cause :)

Med venlig hilsen
Walther

**Comment by wdiechmann** [comment]
hi Thomas,

the SMTP server in question is a

	ESMTP MailEnable Service, Version: 9.75–9.75

and we have other applications (Rails) using it with these settings:

SMTP_HOST=10.0.0.141
SMTP_PORT=25
SMTP_DOMAIN_NAME=wheelstore.space
SMTP_USER=xxxxx
SMTP_PASSWORD=xxxxx
SMTP_AUTHENTICATION=none

I’m sorry but that is about all I can share - without you asking for specifics <:)

But please do - and I will happily try to find out :)



Cheers,
Walther

**Comment by kdisneur** [comment]
Hi, sorry for the late reply.

Could you also send us your Bamboo SMTP configuration?

**Comment by wdiechmann** [comment]
hi - no problem :)

Here is the SMTP config:

  adapter: Bamboo.SMTPAdapter,
  server: "10.0.0.141",
  port: 25,
  username: “xx”,
  password: “xx”,
  tls: :if_available, # can be `:always` or `:never`
  allowed_tls_versions: [:"tlsv1", :"tlsv1.1", :"tlsv1.2"], 
  ssl: false, 
  retries: 1

**Comment by kdisneur** [comment]
The configuration looks right to me.

Is it possible the problem comes from the data? The difference between SendGrid and us might ve the way we format the emails: [here](https://github.com/fewlinesco/bamboo_smtp/blob/develop/lib/bamboo/adapters/smtp_adapter.ex#L225) and [there](https://github.com/fewlinesco/bamboo_smtp/blob/develop/lib/bamboo/adapters/smtp_adapter.ex#L238).

Do you think it's possible you have some data containing special characters we need to escape? Currently, we don't escape anything in the email address or person name.

**Comment by wdiechmann** [comment]
I don’t think so - as long as you handle UTF-8 then we’d be safe to go I say :)

and the ‘to’ formating does look alright to me, too.

Perhaps you better ‘stiff’ this one - and if anybody else comes charging with their hair on fire, we could pull this one down from the shelves and start wondering together once more?

From my point of view it is pure academia right now as SendGrid works - and if I’m the only guy in the room crying wolf, best let it go (at least for now) :)

But thanks again for getting back - and if I stumble upon and hint/smell I’ll let you know first thing!



cheers,
Walther

**Comment by kdisneur** [comment]
I close it for now. 

Thanks for the issue and sorry we didn't manage to understand what happened.
