### ISSUE TITLE
Dynamic Configuration

### ISSUE THREAD

**Issue by crqrdotcom** [fewlinesco/bamboo_smtp#73]
Hello,

I'd like to know if it's possible to somehow store SMTP configuration in a database and configure `bamboo_smtp` at runtime instead of specifying configuration on config file.

Thanks in advance!

**Comment by tgautier** [comment]
Hey,

Actually we already support the SMTP configuration to be specified at runtime through `{:system, "ENV"}` so I guess you could easily swap this out for your database configuration.

Hope it helps!

**Comment by kdisneur** [comment]
Hi @und0ck3d 

Unfortunately we don't read the configuration ourselves. Configuration is read by [Bamboo]( https://github.com/thoughtbot/bamboo) and, as an adapter, we only need to implement a [protocol](https://github.com/thoughtbot/bamboo/blob/master/lib/bamboo/adapter.ex#L37). 

Basically they send us the configuration they read and we have to return a new one. That's all.

I think you can create an issue on the Bamboo repository to ask if it's possible for them to implement this feature. Sorry, but we can't help much with this one. :confused:

**Comment by anthonator** [comment]
It seems there's a concerted effort within the Elixir community to move dynamic config out of `config.exs` files.

Another option would be to require dynamic config from an `init` function within `MyApp.Mailer`. Ecto started taking this approach in version 2.2 (I think?) and Phoenix seems to be making this transition as well.

I'm not sure if this would fulfill @und0ck3d's requirements.

Here's an example of a `Repo` config:

```elixir
def init(_type, config) do
  { :ok, Keyword.put(config, :url, database_url(Mix.env)) }
end

defp database_url(:prod), do: System.get_env("DATABASE_URL")
defp database_url(env), do: "#{System.get_env("DATABASE_URL")}_#{env}"
```

**Comment by anthonator** [comment]
Ah, crap, didn't see @kdisneur's comment.

**Comment by anthonator** [comment]
This could be relevant

https://github.com/thoughtbot/bamboo/issues/309

**Comment by coryodaniel** [comment]
So you can already do dynamic configuration by calling the public undocumented functions `Bamboo.Mailer.deliver_later/3` and `Bamboo.Mailer.deliver_now/3` and pass them the config as the third arg... 

I had opened a ticket for ~[the same thing](https://github.com/thoughtbot/bamboo/issues/309#issuecomment-343047055)

The [mailer macro](https://github.com/thoughtbot/bamboo/blob/master/lib/bamboo/mailer.ex#L63) is pretty trivial. It would be pretty simple to create a custom mailer in your app that *didn't* use this macro and instead got the config from an `{m,f,a}` and called those functions.

```elixir

defmodule MyMailer do
  def deliver_now(email) do
     Bamboo.Mailer.deliver_now(adapter(), email, config())
  end

  def deliver_later(email) do
     Bamboo.Mailer.deliver_now(adapter(), email, config())
  end

  def adapter() do
    # your code to read adapter from ENV / {m,f,a}
  end

  def config() do
    # your code to read config from ENV / {m,f,a}
  end
end
```

**Comment by adkron** [comment]
https://hex.pm/packages/bamboo_config_adapter, I created this for the same reason.

**Comment by tgautier** [comment]
Closed as this can be fixed by using https://github.com/fewlinesco/bamboo_smtp/issues/73#issuecomment-343047396 or 
https://hex.pm/packages/bamboo_config_adapter
