### ISSUE TITLE
:network failure error

### ISSUE THREAD

**Issue by ss13ms110** [fewlinesco/bamboo_smtp#76]
while sending email thorugh MyApp.Mailer.deliver_now I am getting the following error

{:network_failure, 'smtp.gmail.com', {:error, :econnrefused}}

forwarding through POP/IMAP is on in gmail
Please help.

Thanks in advance

**Comment by tgautier** [comment]
Hey,

Have you triple checked your smtp configuration as this kind of error is often due to a problem with credentials and/or tls, etc...

You should check that you use the correct Gmail ports for SMTP which is `587` for `tls` and `465` for `ssl`.

**Comment by tgautier** [comment]
I'm closing this issue, feel free to open it again if the problem persists.
