### ISSUE TITLE
Request for new RC release

### ISSUE THREAD

**Issue by seantanly** [fewlinesco/bamboo_smtp#83]
Can we have a new RC release that includes the commit which addresses warning on Elixir version?

Thank you! :)

**Comment by tgautier** [comment]
Thanks for your message, we will release a new RC very soon 😉

**Comment by tgautier** [comment]
Hey, we've just published a new RC, `1.5.0-rc.3`

You can find it [here](https://hex.pm/packages/bamboo_smtp/1.5.0-rc.3) or update your `mix.exs`
