### ISSUE TITLE
Anyone having email addresses get cut off?

### ISSUE THREAD

**Issue by mkaplan9** [fewlinesco/bamboo_smtp#86]
I am attempting to send an email to an address like xxx@yyy.health and somewhere in the process it's getting truncated to xxx@yyy.heal 

I believe it's truncating the part after the period to 4 characters but couldn't track down where that was occurring in this library, Bamboo, or Mailman. Any help would be greatly appreciated!

Thanks!

**Comment by kdisneur** [comment]
Hello @mkaplan9 

We just looked at our code (trying to output some debug) and we don't see any problem on Bamboo nor BambooSMTP. Here the output we send to `gen_smtp` when using `jane@doe.areallylongtld` as email:

```
{"john@doe.areallylongtld", ["jane@doe.areallylongtld"],
 "Subject: =?UTF-8?B?V2VsY29tZQ==?=\r\nFrom: john@doe.areallylongtld\r\nBcc: \r\nCc: \r\nTo: jane@doe.areallylongtld\r\nMIME-Version: 1.0\r\nContent-Type: multipart/mixed; boundary=\"----=_Part_289344873_20812845.69600832\"\r\n\r\n------=_Part_289344873_20812845.69600832\r\nContent-Type: multipart/alternative; boundary=\"----=_Part_3145581418_575136179.927653135\"\r\n\r\n------=_Part_3145581418_575136179.927653135\r\nContent-Type: text/plain;charset=UTF-8\r\n\r\nWelcome!\r\n------=_Part_3145581418_575136179.927653135--\r\n------=_Part_289344873_20812845.69600832--\r\n"}
```

The data seems correct.

I also tried really sending an email using and the debug output is:

```
%Bamboo.Email{assigns: %{}, attachments: [], bcc: [], cc: [], from: {nil, "<my-own-email-address>"}, headers: %{}, html_body: nil, private: %{}, subject: "Welcome", text_body: "Welcome!", to: [nil: "nothin@adomain.areallylongtld"]}
"2.0.0 OK 1523606235 w14sm935090wmd.1 - gsmtp\r\n"
```

So it looks like `gen_smtp` also works as expected. 

We can let the issue open for a while in case someone else have idea but unfortunately I don't know how to help you more with that... Sorry.

**Comment by mkaplan9** [comment]
Thanks for your quick reply and for looking into it! I will keep digging on my end and let you know if I make any discoveries.

**Comment by kdisneur** [comment]
Since we have no update since April, we will close the issue. If you have some more information to share about issue, do not hesitate to reopen it.
