### ISSUE TITLE
Bamboo 1.0 support

### ISSUE THREAD

**Issue by tomciopp** [fewlinesco/bamboo_smtp#93]
I noticed that thoughtbot recently shipped v1 of Bamboo. I've seen a few release candidates for 1.5 that support the newest version. I would be happy to help out if there is anything that needs to be done to support the release.

**Comment by tgautier** [comment]
Hey, thanks for the update.

We will release a new stable version of `bamboo_smtp` real soon.

**Comment by kdisneur** [comment]
@tomciopp Thanks for the issue! We just bumped to Bamboo 1.0.0 and published the new version: https://hex.pm/packages/bamboo_smtp
