### ISSUE TITLE
Large memory usage when sending emails with an attachment

### ISSUE THREAD

**Issue by fsanggang** [fewlinesco/bamboo_smtp#96]
I am using `bamboo` and `bamboo_smtp` to send a text email with a PDF file as an attachment. The PDF file is ~1.8MB. Memory usage consistently hovered around 1.7MB as the `%Bamboo.Email` is generated. However on calling `.deliver`, memory usage grew to ~2.5 GB. This increase in memory usage was also observed for emails without attachments, although the increase was not as drastic. Is this expected behaviour?

`bamboo` version v1.0.0 
`bamboo_smtp` version v1.5.0

**Comment by kdisneur** [comment]
Hi @fsanggang 

Thank you for the bug report! The current implementation is based on String concatenation which is probably not the best.

I tried to rewrite it using IO lists and the implementation seems to work but I don't know if it's going to help much in terms of performance (I don't see much difference when testing but I didn't have memory usage growing to 2.5GB either).

Could you try sending some of your emails with this branch: [feature/try_iolist_impl](https://github.com/fewlinesco/bamboo_smtp/tree/feature/try_iolist_impl) and let us know if it helps somehow?

For the attachment part, I can imagine how [this function](https://github.com/fewlinesco/bamboo_smtp/blob/feature/try_iolist_impl/lib/bamboo/adapters/smtp_adapter.ex#L212...L221) is not optimized but don't know how to really improve it. 

If you have some ideas, do not hesitate to share them with us 😸 

Thanks again

**Comment by kdisneur** [comment]
I will close this issue as we have no update since June. If you have more information to share or the time to test the branch [feature/try_iolist_impl](https://github.com/fewlinesco/bamboo_smtp/tree/feature/try_iolist_imp), do not hesitate to reopen the issue.
