### ISSUE TITLE
How can I specify username/password per email?

### ISSUE THREAD

**Issue by GildedHonour** [fewlinesco/bamboo_smtp#97]
I want to send different emails from different accounts of the same server. How can I specify username/password per email?

**Comment by kdisneur** [comment]
Hi @GildedHonour 

In a project when we have an SMTP configuration for each of our clients, we directly use a function exposed by [Bamboo.Mailer][BAMBOO].

You can also find some information in this issue: https://github.com/fewlinesco/bamboo_smtp/issues/73#issuecomment-343047396

Does this help?

[BAMBOO]: https://github.com/thoughtbot/bamboo/blob/master/lib/bamboo/mailer.ex#L116

**Comment by GildedHonour** [comment]
thx
